
# Apply MySQL:3306 to outer traffic

apiVersion: v1
kind: Service
metadata:
  name: mysql-0-service
  namespace: mysql
spec:
  type: ClusterIP

  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-0

  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-0-route
  namespace: mysql
spec:
  entryPoints:
    - mysql

  routes:
    - match: HostSNI(`*`)
      services:
        - name: mysql-0-service
          port: 3306