
# Vi du ve trien khai Job chay tuan tu (su dung PreSync + Sync-Wave trong ArgoCD
# PreSync giup cho Job nay duoc uu tien chay truoc cac Resource khac
# Sync-Wave giup dam bao thu tu giua cac Jobs duoc chay.

# Job nay se duoc kich hoat 1 lan
apiVersion: batch/v1
kind: Job
metadata:
  name: job2
  namespace: test-job-run-in-sequence
  annotations:
    argocd.argoproj.io/hook: PreSync
    # Gia tri sync-wave thap hon : job2 chay sau job1
    argocd.argoproj.io/sync-wave: "-20"

    # Truoc khi execute job thi se tien hanh xoa Job cu (neu co)
    # HookSucceeded cung xoa Job nay khi xu ly thanh cong ...
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300

  template:
    metadata:
      labels:
        app: job2
    spec:
      restartPolicy: Never

      containers:
        - name: seed-data
          image: alpine:3.20

          command:
            - /bin/sh
            - -c
            - |
              echo "We will seed data before initialization resources $(date '+%d/%b/%Y %H:%M:%S')"

              echo "Starting seed data ..."
              sleep 10

              echo "Finish SEED data successfully ... "
              exit 0

