apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: apps
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
